/* Build the frontend as a static bundle for a host like Vercel.
 *
 *   PRINTBRIDGE_API_URL=https://printbridge.tailnet-1234.ts.net npm run build:web
 *
 * What it does: copies public/ to dist/, and writes dist/config.js pointing the
 * frontend at that backend URL. Nothing is compiled — the app is plain ES
 * modules — so this has no dependencies and cannot fail on a native build.
 *
 *   PRINTBRIDGE_API_URL    origin of the backend (required, unless "same-origin")
 *   PRINTBRIDGE_ADMIN_URL  optional: where the admin console lives, when it is
 *                          not /admin on the frontend's own origin
 *   OUT_DIR                optional: output directory (default dist)
 *
 * The backend must list the frontend's origin in ALLOWED_ORIGINS, otherwise the
 * browser blocks every call. See docs/deploy.md.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'public');
const OUT = path.resolve(ROOT, process.env.OUT_DIR || 'dist');

function normalize(value) {
  return String(value || '').trim().replace(/\/+$/, '');
}

function fail(message) {
  console.error(`\n  build:web failed — ${message}\n`);
  process.exit(1);
}

const rawApi = normalize(process.env.PRINTBRIDGE_API_URL);
const apiBase = /^same-origin$/i.test(rawApi) ? '' : rawApi;
const adminUrl = normalize(process.env.PRINTBRIDGE_ADMIN_URL);

if (!apiBase && !/^same-origin$/i.test(rawApi)) {
  fail([
    'PRINTBRIDGE_API_URL is not set.',
    '',
    '  A static deploy has to know where the backend lives:',
    '    PRINTBRIDGE_API_URL=https://your-backend-host npm run build:web',
    '',
    '  If this bundle will be served BY the backend itself, say so explicitly:',
    '    PRINTBRIDGE_API_URL=same-origin npm run build:web',
  ].join('\n  '));
}
if (apiBase && !/^https?:\/\/[^/\s]+$/.test(apiBase)) {
  fail(`PRINTBRIDGE_API_URL must be an origin like https://example.com (got "${apiBase}")`);
}
if (adminUrl && !/^https?:\/\/[^/\s]+$/.test(adminUrl)) {
  fail(`PRINTBRIDGE_ADMIN_URL must be an origin like https://example.com (got "${adminUrl}")`);
}

/* ---------------- copy ---------------- */

fs.rmSync(OUT, { recursive: true, force: true });
fs.cpSync(SRC, OUT, { recursive: true });

/* ---------------- runtime config ---------------- */

const config = `/* Generated by scripts/build-web.cjs — do not edit in the output directory. */
window.PRINTBRIDGE_CONFIG = {
  apiBase: ${JSON.stringify(apiBase)},
  adminUrl: ${JSON.stringify(adminUrl)},
};
`;
fs.writeFileSync(path.join(OUT, 'config.js'), config);

/* A small deployment fingerprint, useful when checking what is live. */
fs.writeFileSync(path.join(OUT, 'deployment.json'), JSON.stringify({
  builtAt: new Date().toISOString(),
  apiBase: apiBase || '(same origin as this page)',
  adminUrl: adminUrl || '(this origin)',
  version: require(path.join(ROOT, 'package.json')).version,
}, null, 2) + '\n');

/* ---------------- report ---------------- */

const files = [];
(function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(path.relative(OUT, full));
  }
})(OUT);

console.log('');
console.log('  frontend bundle built');
console.log(`  output      ${path.relative(ROOT, OUT)} (${files.length} files)`);
console.log(`  apiBase     ${apiBase || '(same origin as this page)'}`);
console.log(`  adminUrl    ${adminUrl || '(this origin)'}`);
console.log('');
console.log('  Remember to allow this site on the backend:');
console.log(`    ALLOWED_ORIGINS=https://<this-site's-domain>`);
console.log('');
