/* Build the frontend as a static bundle for a host like Vercel.
 *
 *   PRINTBRIDGE_API_URL=https://printbridge.tailnet-1234.ts.net npm run build:web
 *
 * PRINTBRIDGE_ADMIN_URL is optional: the origin of the control room. The main
 * site's Admin button points there (the console itself is never in this bundle,
 * because only the machine holding the printer can run it). It defaults to the
 * API origin, which is where /admin actually lives on a normal install.
 *
 * What it does: copies public/ to dist/, and writes dist/config.js pointing the
 * frontend at that backend URL. Nothing is compiled — the app is plain ES
 * modules — so this has no dependencies and cannot fail on a native build.
 *
 *   PRINTBRIDGE_API_URL    origin of the backend (required, unless "same-origin")
 *   OUT_DIR                optional: output directory (default dist)
 *
 * public/admin/ is deliberately NOT copied: this bundle is the public guest
 * site, and the control room stays on the machine that runs the server. A
 * static host therefore cannot serve somebody an admin console to poke at.
 *
 * The backend must list the frontend's origin in ALLOWED_ORIGINS, otherwise the
 * browser blocks every call. See docs/deploy.md.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'public');
const OUT = path.resolve(ROOT, process.env.OUT_DIR || 'dist');

function normalize(value) {
  return String(value || '').trim().replace(/\/+$/, '');
}

function fail(message) {
  console.error(`\n  build:web failed — ${message}\n`);
  process.exit(1);
}

const rawApi = normalize(process.env.PRINTBRIDGE_API_URL);
const apiBase = /^same-origin$/i.test(rawApi) ? '' : rawApi;

if (!apiBase && !/^same-origin$/i.test(rawApi)) {
  fail([
    'PRINTBRIDGE_API_URL is not set.',
    '',
    '  A static deploy has to know where the backend lives:',
    '    PRINTBRIDGE_API_URL=https://your-backend-host npm run build:web',
    '',
    '  If this bundle will be served BY the backend itself, say so explicitly:',
    '    PRINTBRIDGE_API_URL=same-origin npm run build:web',
  ].join('\n  '));
}
if (apiBase && !/^https?:\/\/[^/\s]+$/.test(apiBase)) {
  fail(`PRINTBRIDGE_API_URL must be an origin like https://example.com (got "${apiBase}")`);
}
/* ---------------- copy ---------------- */

fs.rmSync(OUT, { recursive: true, force: true });
fs.cpSync(SRC, OUT, {
  recursive: true,
  // The guest site only. Nothing in this bundle can reach the console, and the
  // console is not on this host to be fetched in the first place.
  filter: (source) => path.basename(source) !== 'admin',
});

/* ---------------- runtime config ---------------- */

const rawAdmin = normalize(process.env.PRINTBRIDGE_ADMIN_URL);
const adminBase = rawAdmin && !/^same-origin$/i.test(rawAdmin) ? rawAdmin : (rawAdmin ? '' : apiBase);
if (adminBase && !/^https?:\/\/[^/\s]+$/.test(adminBase)) {
  fail(`PRINTBRIDGE_ADMIN_URL must be an origin like https://example.com (got "${adminBase}")`);
}

const config = `/* Generated by scripts/build-web.cjs — do not edit in the output directory. */
window.PRINTBRIDGE_CONFIG = {
  apiBase: ${JSON.stringify(apiBase)},
  adminBase: ${JSON.stringify(adminBase)},
};
`;
fs.writeFileSync(path.join(OUT, 'config.js'), config);

/* A small deployment fingerprint, useful when checking what is live. */
fs.writeFileSync(path.join(OUT, 'deployment.json'), JSON.stringify({
  builtAt: new Date().toISOString(),
  apiBase: apiBase || '(same origin as this page)',
  adminBase: adminBase || '(same origin as this page)',
  includesAdmin: false,
  version: require(path.join(ROOT, 'package.json')).version,
}, null, 2) + '\n');

/* ---------------- report ---------------- */

const files = [];
(function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(path.relative(OUT, full));
  }
})(OUT);

console.log('');
console.log('  frontend bundle built');
console.log(`  output      ${path.relative(ROOT, OUT)} (${files.length} files)`);
console.log(`  apiBase     ${apiBase || '(same origin as this page)'}`);
console.log(`  adminBase   ${adminBase || '(same origin as this page)'}`);
console.log('  admin       not included (the console lives on the print server)');
console.log('');
console.log('  Remember to allow this site on the backend:');
console.log(`    ALLOWED_ORIGINS=https://<this-site's-domain>`);
console.log('');
