/* Build the frontend as a static bundle for a host like Vercel.
 *
 *   PRINTBRIDGE_API_URL=https://printbridge.tailnet-1234.ts.net npm run build:web
 *
 * PRINTBRIDGE_ADMIN_URL is optional: the origin of the control room. The main
 * site's Admin button points there (the console itself is never in this bundle,
 * because only the machine holding the printer can run it). It defaults to the
 * API origin, which is where /admin actually lives on a normal install.
 *
 * What it does: copies public/ to dist/, and writes dist/config.js pointing the
 * frontend at that backend URL. Nothing is compiled — the app is plain ES
 * modules — so this has no dependencies and cannot fail on a native build.
 *
 *   PRINTBRIDGE_API_URL    origin of the backend (required, unless "same-origin")
 *   OUT_DIR                optional: output directory (default dist)
 *
 * The console is deliberately NOT here: it is part of the desktop app, served
 * on loopback by that app, so a static host has nothing administrative to hand
 * out even by accident.
 *
 * The backend must list the frontend's origin in ALLOWED_ORIGINS, otherwise the
 * browser blocks every call. See docs/deploy.md.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'public');
const OUT = path.resolve(ROOT, process.env.OUT_DIR || 'dist');

function normalize(value) {
  return String(value || '').trim().replace(/\/+$/, '');
}

function fail(message) {
  console.error(`\n  build:web failed — ${message}\n`);
  process.exit(1);
}

const rawApi = normalize(process.env.PRINTBRIDGE_API_URL);
const apiBase = /^same-origin$/i.test(rawApi) ? '' : rawApi;

if (!apiBase && !/^same-origin$/i.test(rawApi)) {
  fail([
    'PRINTBRIDGE_API_URL is not set.',
    '',
    '  A static deploy has to know where the backend lives:',
    '    PRINTBRIDGE_API_URL=https://your-backend-host npm run build:web',
    '',
    '  If this bundle will be served BY the backend itself, say so explicitly:',
    '    PRINTBRIDGE_API_URL=same-origin npm run build:web',
  ].join('\n  '));
}
if (apiBase && !/^https?:\/\/[^/\s]+$/.test(apiBase)) {
  fail(`PRINTBRIDGE_API_URL must be an origin like https://example.com (got "${apiBase}")`);
}
/* ---------------- copy ---------------- */

/* Nothing is withheld from this bundle any more, and the reason is worth
 * writing down. `owner/` used to be excluded, because its session cookie was
 * same-site only — on a static host that page could sign in and then lose the
 * session on the next request. That is now handled where it belongs: the cookie
 * is built SameSite=None; Secure for an allowlisted cross-site origin
 * (src/cookies.js), so the page works from the site and from this machine.
 *
 * It has to be here besides: the whole sale ends on it. A buyer pays, gets a
 * code by email, and registers at /owner — a deploy that answers /owner with
 * the marketing page is a dead end.
 *
 * The *machine* console is a different thing and is not part of this bundle at
 * all: it lives in desktop/renderer/ and ships inside the desktop app. */

fs.rmSync(OUT, { recursive: true, force: true });
fs.cpSync(SRC, OUT, { recursive: true });

/* ---------------- the floor ---------------- */

/* Every page that links a stylesheet must carry an inline one before it.
 *
 * The inline icons have no size of their own, so a page whose stylesheet is
 * slow — or blocked, or lost to a flaky connection at the printer — paints one
 * enormous printer icon at the width of the phone and reads as broken. The
 * floor fixes that, and it is the kind of thing a redesign deletes by accident,
 * so the build checks it rather than trusting anybody to remember. */
const FLOOR_PAGES = ['index.html', 'print/index.html', 'owner/index.html'];
for (const page of FLOOR_PAGES) {
  const file = path.join(OUT, page);
  if (!fs.existsSync(file)) { fail(`${page} is missing from the bundle`); }
  const html = fs.readFileSync(file, 'utf8');
  const style = html.indexOf('<style>');
  const sheet = html.search(/<link[^>]+rel=["']stylesheet["']/);
  if (sheet !== -1 && (style === -1 || style > sheet)) {
    fail(`${page} links a stylesheet without an inline floor before it —\n  an unstyled paint is one huge icon. See the <style> block at the top of ${page}.`);
  }
}

/* ---------------- runtime config ---------------- */

const rawAdmin = normalize(process.env.PRINTBRIDGE_ADMIN_URL);
const adminBase = rawAdmin && !/^same-origin$/i.test(rawAdmin) ? rawAdmin : (rawAdmin ? '' : apiBase);
if (adminBase && !/^https?:\/\/[^/\s]+$/.test(adminBase)) {
  fail(`PRINTBRIDGE_ADMIN_URL must be an origin like https://example.com (got "${adminBase}")`);
}

const config = `/* Generated by scripts/build-web.cjs — do not edit in the output directory. */
window.PRINTBRIDGE_CONFIG = {
  apiBase: ${JSON.stringify(apiBase)},
  adminBase: ${JSON.stringify(adminBase)},
};
`;
fs.writeFileSync(path.join(OUT, 'config.js'), config);

/* A small deployment fingerprint, useful when checking what is live. */
fs.writeFileSync(path.join(OUT, 'deployment.json'), JSON.stringify({
  builtAt: new Date().toISOString(),
  apiBase: apiBase || '(same origin as this page)',
  adminBase: adminBase || '(same origin as this page)',
  includesAdmin: false,
  includesDesktop: false,
  includesOwner: true,
  version: require(path.join(ROOT, 'package.json')).version,
}, null, 2) + '\n');

/* ---------------- report ---------------- */

const files = [];
(function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(path.relative(OUT, full));
  }
})(OUT);

console.log('');
console.log('  frontend bundle built');
console.log(`  output      ${path.relative(ROOT, OUT)} (${files.length} files)`);
console.log(`  apiBase     ${apiBase || '(same origin as this page)'}`);
console.log(`  adminBase   ${adminBase || '(same origin as this page)'}`);
console.log('  owner/      included — buyers register there after checkout');
console.log('');
console.log('  Remember to allow this site on the backend:');
console.log(`    ALLOWED_ORIGINS=https://<this-site's-domain>`);
console.log('');
